<h1> Assignment 2 for CS 603</h1>

<h3>Mohamed Fazmi Ahamed Fizer </h3>
<h3>Hari Charan Kaveri </h3>
<h3>Tharinda Embuldeniya </h3>

In [9]:
import json
import itertools as it

class Employee: #same as Employee(object)
    'Common base class for all employees'
    empCount = 0 #class attribute
    
    #name, salary and _age are instance attributes
    def __init__(self, name, salary, age): #initializer must have at least argument beside self
        self.name = name
        self.salary = salary
        self.age = age
        Employee.empCount += 1
   
    def displayCount(self):
        print("Total Employee: {0}".format(Employee.empCount))

    def displayEmployee(self):
        print("Name : {0}, \tSalary: {1}, \tAge: {2}".format(self.name,self.salary, self.__age))
        
    def work(self):
        return "%s is working" % (self.name)
    
    def toString(self):
        return "Name : {0}, Salary: {1}, Age: {2}".format(self.name,self.salary, self.age)
    
    def getAge(self):
        return self.age

In [11]:


employees = [Employee ("James", 10000, 22),
            Employee ("Reed", 15000, 24),
            Employee ("Naomi", 28000,28),
            Employee ("John", 22000,25),
            Employee ("fnn", 25000,27)]


for x in employees:
    x.displayEmployee()


'''''
employees.sort (key=lambda x:x.salary ,reverse = True)
 
print("\nTop 3 Employees  with Highest Salaries \n")
data =  [emp.displayEmployee() for emp in employees[:3] ]

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-11-c2bc0ad3ab80>, line 18)

In [6]:
class Company:
    Employee = []
       
    def __init__(self,Employee):
        self.Employee = Employee
        
    def work (self):
        for emp in self.Employee:
            print(emp.work())

emp1 = Employee ("James", 10000, 22)
emp2 = Employee ("Reed", 15000,24)
emp3 = Employee ("Naomi", 28000,28)
emp4 = Employee ("John", 22000,25)
emp5 = Employee ("Ann", 25000,27)

company = Company([emp1,emp2,emp3,emp4,emp5])

print("\nCalling the Company: working\n")
company.work()

Calling the Company: working

James is working
Reed is working
Naomi is working
John is working
Ann is working

In [23]:
### path to file 
with open ("/Users/techyouknow/Dropbox/SEMO/Class/Spring 19/CS 603/Assignment2/qfour.json") as file:
    jdata = json.load(file)
file.close()

employ_data  = [itm for lines in jdata.values() for itm in lines]

print (employ_data)

#generator 
def getEmployeeData(sqx):
    for x in sqx:
        yield x
        
emp_list = []

for ent in getEmployeeData (employ_data):
    tmp = Employee(ent["name"],ent["salary"], ent["age"])
    emp_list.append(tmp)
    
# sort employees by their name
emp_list.sort (key = lambda x :x.name)

# salary increase 5% 
for e in getEmployeeData(emp_list):
    e.salary *= 1.05

# create new dictionary with keys ranging to 10 
emp_dic = {}
for key , value in enumerate(getEmployeeData(emp_list)):
    emp_dic.update ({key : value})
    
print ("\nKey Value pair for sorted by Employee Name") 
for key , value in emp_dic.items():
    print ("key:", key +1, "value:", value.toString())

emp_list.sort (key = lambda x :x.getAge())    
print ("\nEmployee Age Group")    
#age groups
def age_group(age):
    if age <= 20:
        return "\nyounger than 20"
    elif 20 < age  <= 30:
        return "\n21-30"
    elif 31 < age <= 50:
        return "\n31-50"
    elif 50 < age <= 65:
        return "\n51-65"
    else:
        return "\nolder than 65"

# using itertools groupby  for age
for key, grp in it.groupby(emp_list, lambda x: age_group (x.getAge())):
    print(key)

    for e in grp:
        print (e.toString())

[{'name': 'Sam', 'age': 22, 'salary': 2000}, {'name': 'Ram', 'age': 56, 'salary': 85400}, {'name': 'Tintin', 'age': 76, 'salary': 58780}, {'name': 'Pam', 'age': 14, 'salary': 6000}, {'name': 'Queen', 'age': 42, 'salary': 22000}, {'name': 'Oswald', 'age': 66, 'salary': 28750}, {'name': 'Chi', 'age': 37, 'salary': 38780}, {'name': 'Troy', 'age': 34, 'salary': 6785}, {'name': 'Kane', 'age': 69, 'salary': 188780}, {'name': 'Suriya', 'age': 88, 'salary': 36785}]

Key Value pair for sorted by Employee Name
key: 1 value: Name : Chi, Salary: 40719.0, Age: 37
key: 2 value: Name : Kane, Salary: 198219.0, Age: 69
key: 3 value: Name : Oswald, Salary: 30187.5, Age: 66
key: 4 value: Name : Pam, Salary: 6300.0, Age: 14
key: 5 value: Name : Queen, Salary: 23100.0, Age: 42
key: 6 value: Name : Ram, Salary: 89670.0, Age: 56
key: 7 value: Name : Sam, Salary: 2100.0, Age: 22
key: 8 value: Name : Suriya, Salary: 38624.25, Age: 88
key: 9 value: Name : Tintin, Salary: 61719.0, Age: 76
key: 10 value: Name : Troy, Salary: 7124.25, Age: 34

Employee Age Group

younger than 20
Name : Pam, Salary: 6300.0, Age: 14

21-30
Name : Sam, Salary: 2100.0, Age: 22

31-50
Name : Troy, Salary: 7124.25, Age: 34
Name : Chi, Salary: 40719.0, Age: 37
Name : Queen, Salary: 23100.0, Age: 42

51-65
Name : Ram, Salary: 89670.0, Age: 56

older than 65
Name : Oswald, Salary: 30187.5, Age: 66
Name : Kane, Salary: 198219.0, Age: 69
Name : Tintin, Salary: 61719.0, Age: 76
Name : Suriya, Salary: 38624.25, Age: 88

In [26]:
#subclass
from collections import UserDict
class EmployeeD(UserDict):
    
    def __getitem__(self, key):
        return super().__getitem__(key)
    
    def __setitem__(self,key,value):
        return super().__setitem__(key,value)

empD_list = []

for x in emp_list:
    temp = EmployeeD(name=x.name, salary=x.salary, age= x.getAge())
    empD_list.append(temp)

total_sal = 0

#using earlier generator function
for emp in getEmployeeData(empD_list):
    total_sal += emp.__getitem__("salary")

print("\n Total Salary for Employees :", total_sal)

 Total Salary for Employees : 497763.0

In [28]:
# last Question 
from collections import namedtuple
import csv
import itertools as it
import functools as ft

class DataPoint(namedtuple("DataPoint", ["home_type", "value"])):
    __slots__ = ()

def read_prices(csvfile):
    with open(csvfile) as infile:
        reader = csv.DictReader(infile)
        for row in reader:
                yield DataPoint(
                home_type=(row["type" ]),
                value=float(row["price"]),
            )
# Read prices 
prices = tuple(read_prices("/Users/techyouknow/Desktop/Sacramentorealestatetransactions.csv"))


# type  
condo = tuple (DataPoint (it[0],it[1]) for it in prices if it[0] == 'Condo')
multi= tuple (DataPoint (it[0],it[1]) for it in prices if it[0] == 'Multi-Family')
res =  tuple (DataPoint (it[0],it[1]) for it in prices if it[0] == 'Residential')

# Condo
print("\nReal Estate Pricing for Condo")
zdp = DataPoint(None, 0)  # zero DataPoint
max_price = ft.reduce(max, condo)
min_price = ft.reduce(min, condo)

print("Highest Transaction: {1} on {0}".format(*max_price))
print("Lowest Transaction: {1} on {0}".format(*min_price))

# Multi-Family
print("\nReal Estate Pricing for Multi-Family")
zdp = DataPoint(None, 0)  # zero DataPoint
max_price = ft.reduce(max, multi)
min_price = ft.reduce(min, multi)

print("Highest Transaction: {1} on {0}".format(*max_price))
print("Lowest Transaction: {1} on {0}".format(*min_price))

# Residential .
print("\nReal Estate Pricing for Residential")
zdp = DataPoint(None, 0)  # zero DataPoint
max_price = ft.reduce(max, res)
min_price = ft.reduce(min, res)

print("Highest Transaction: {1} on {0}".format(*max_price))
print("Lowest Transaction: {1} on {0}".format(*min_price))

Real Estate Pricing for Condo
Highest Transaction: 360000.0 on Condo
Lowest Transaction: 40000.0 on Condo

Real Estate Pricing for Multi-Family
Highest Transaction: 416767.0 on Multi-Family
Lowest Transaction: 100000.0 on Multi-Family

Real Estate Pricing for Residential
Highest Transaction: 884790.0 on Residential
Lowest Transaction: 1551.0 on Residential